### ISSUE TITLE
Panic when using float64 value for language version instead of string in yml file

### ISSUE THREAD

**Issue by srishanbhattarai** [PaulRosset/previs#1]
For example, in `.travis.yml`, the following works:

```yml
language: go
go: "1.9"

# this works
```

However, if I unquote the `"1.9"` then `previs` will panic even though this is still a valid travis config.
```yml
language: go
go: 1.9

# this panics
```

I traced the offending section to:
https://github.com/PaulRosset/previs/blob/9f0ed563801002b327ed2092a78cb2b14b49079c/api/createConf.go#L39-L56

As noted in the Go [documentation](https://golang.org/pkg/reflect/#Value.Index) for the `Index` method.
```
func (v Value) Index(i int) Value

Index returns v's i'th element. It panics if v's Kind is not Array, Slice, or String or i is out of range.
```
